#!/bin/bash

if [[ "$1" = "" ]]; then
    echo 'No class name specified.'
    exit 1
fi

touch $1.{h,cpp}
MNAME=_`echo $1 | tr a-z A-Z`_H_

echo $MNAME

echo "#ifndef $MNAME" > $1.h
echo "#define $MNAME" >> $1.h
echo >> $1.h
echo "class $1" >> $1.h
echo "{" >> $1.h
echo >> $1.h
echo "};" >> $1.h
echo "#endif // $MNAME" >> $1.h

echo "#include \"$1.h\"" > $1.cpp
echo >> $1.cpp

